name: genomePlotter
channels:
  - conda-forge
  - bioconda
  - anaconda
  - conda-canary
  - defaults
dependencies:
  - cairo=1.14
  - numpy=1.19
  - numpy-base=1.19
  - pandas=1.1.3
  - pybedtools=0.7.10
  - bedtools=2.30
  - codacy-coverage=1.3.11
  - python=3.6