version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(module)s - %(funcName)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: genome_plotter.log
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console,file]